services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-Backend
    container_name: backend
    ports:
      - "5002:5002"
    volumes:
      - ./job-pair-backend:/app
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-Frontend
    container_name: frontend
    ports:
      - "8000:8000"
    volumes:
      - ./job-pair-frontend:/app